title: "My Blog"
description: "This is my personal blog"
baseurl: ""
url: "https://hh-hdd.github.io"

# Theme settings
jekyll-remote-theme: slate

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
